(function(){
'use strict';
const SHEET='Morning Run Out',$=id=>document.getElementById(id);let remote=[];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>String(v??'').trim().toLowerCase().replace(/\s+/g,' ');
function iso(d=new Date()){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function toIso(v){const s=String(v||'').trim(),a=s.match(/^(\d{4})-(\d{2})-(\d{2})$/);if(a)return s;const b=s.match(/^(\d{1,2})\/(\d{1,2})\/(\d{2,4})$/);if(b)return `${b[3].length===2?'20'+b[3]:b[3]}-${String(b[2]).padStart(2,'0')}-${String(b[1]).padStart(2,'0')}`;return''}
function uk(v){const m=String(v||'').match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?`${m[3]}/${m[2]}/${m[1]}`:v}
function hm(){return new Date().toLocaleTimeString('en-GB',{hour:'2-digit',minute:'2-digit',hour12:false})}
function mins(v){const m=String(v||'').match(/^(\d{1,2}):(\d{2})/);return m?+m[1]*60+ +m[2]:null}
function diff(s,a){const x=mins(s),y=mins(a);if(x===null||y===null)return null;let d=y-x;if(d<-720)d+=1440;if(d>720)d-=1440;return d}
function text(d){if(d===null)return'';if(d<0)return`${-d} min early`;if(!d)return'On time';if(d<6)return`${d} min late — within tolerance`;return`${d} min late`}
function cls(d){return d>=6?'late':d>0?'tol':'good'}
function key(r){return [toIso(r[0]),r[1],r[2],r[3],r[5],r[8],r[9]].map(norm).join('|')}
function local(){try{const x=JSON.parse(localStorage.getItem('local_'+SHEET)||'[]');return Array.isArray(x)?x:[]}catch(e){return[]}}
function rows(){const a=remote.length&&norm(remote[0]?.[3])==='duty number'?remote.slice(1):remote,m=new Map();[...local(),...a].forEach(r=>Array.isArray(r)&&r[0]&&r[3]&&m.set(key(r),r));return[...m.values()]}
function current(){const d=$('mroDate')?.value||iso();return rows().filter(r=>toIso(r[0])===d).sort((a,b)=>String(a[8]).localeCompare(String(b[8])))}
function stats(a){const c=a.filter(r=>diff(r[8],r[9])!==null),late=c.filter(r=>diff(r[8],r[9])>=6).length;return{total:c.length,late,on:c.length-late,p:c.length?(c.length-late)/c.length*100:0}}
function live(){const d=diff($('mroScheduled')?.value,$('mroActual')?.value),e=$('mroLive');if(!e)return;e.className='mroLive '+(d===null?'':cls(d));e.textContent=d===null?'Enter scheduled and actual time':text(d)}
function render(){const a=current(),list=$('mroList'),sum=$('mroSummary');if(!list||!sum)return;list.innerHTML=a.map(r=>{const d=diff(r[8],r[9]);return`<div class="mroCard ${cls(d)}"><div class="mroTop"><div><b>Duty ${esc(r[3])} • ${esc(r[4])}</b><span>Fleet ${esc(r[5])} • ${esc(r[8])} → ${esc(r[9])}</span></div><strong>${esc(text(d))}</strong></div><div class="mroTags"><span class="${norm(r[6])==='yes'?'ok':'bad'}">DQC ${norm(r[6])==='yes'?'✓':'✕'}</span><span class="${norm(r[7])==='yes'?'ok':'bad'}">Destination ${norm(r[7])==='yes'?'✓':'✕'}</span><span>${esc(r[2]||'-')}</span></div>${r[12]?`<div class="mroComment">${esc(r[12])}</div>`:''}</div>`}).join('')||'<div class="panel">No Morning Run Out entries for this date.</div>';const s=stats(a);sum.innerHTML=`<div><small>TOTAL BUSES CHECKED</small><b>${s.total}</b></div><div><small>ON TIME / WITHIN 5 MIN</small><b>${s.on}</b></div><div><small>6+ MIN LATE</small><b>${s.late}</b></div><div class="score"><small>RUN OUT SCORE</small><b>${s.p.toFixed(1)}%</b></div>`}
function clear(){['mroDuty','mroName','mroFleet','mroScheduled','mroActual','mroComments'].forEach(id=>$(id).value='');$('mroDqc').checked=$('mroDest').checked=true;live();$('mroDuty').focus()}
function save(){const duty=$('mroDuty').value.trim(),name=$('mroName').value.trim(),fleet=$('mroFleet').value.trim(),s=$('mroScheduled').value,a=$('mroActual').value;if(!duty||!name||!fleet||!s||!a){alert('Please enter Duty Number, Name, Fleet Number, Scheduled Time and Actual Time Out.');return}const d=diff(s,a),date=$('mroDate').value,row=[uk(date),hm(),typeof getInspector==='function'?getInspector():'',duty,name,fleet,$('mroDqc').checked?'Yes':'No',$('mroDest').checked?'Yes':'No',s,a,d,d>=6?'LATE 6+':d<0?'EARLY':'ON TIME',$('mroComments').value.trim(),date];if(!remote.length)remote=[['Date','Saved Time','Inspector','Duty Number','Name','Fleet Number','DQC','Correct Destination','Scheduled Time','Actual Time Out','Minutes Early/Late','Status','Comments','Run ID']];remote.push(row);if(typeof cloudAppend==='function')cloudAppend(SHEET,row);clear();render();setTimeout(load,1400)}
async function load(){try{const j=WEB_APP_URL.includes('?')?'&':'?',res=await fetch(WEB_APP_URL+j+'sheet='+encodeURIComponent(SHEET)+'&_='+Date.now(),{cache:'no-store'}),x=await res.json();if(x&&Array.isArray(x.data)){remote=x.data;if(typeof cloud!=='undefined')cloud[SHEET]=x.data}}catch(e){}render()}
function exportExcel(){const a=current();if(!a.length){alert('There are no entries to export for this date.');return}const s=stats(a),date=$('mroDate').value,head=['DUTY NO','NAME','FLEET NUMBER','DQC','CORRECT DESTINATION','SCHEDULED','ACTUAL','MIN EARLY/LATE','STATUS','COMMENTS'],body=a.map(r=>[r[3],r[4],r[5],r[6],r[7],r[8],r[9],r[10],r[11],r[12]]),table=[head,...body].map(row=>'<tr>'+row.map(v=>`<td>${esc(v)}</td>`).join('')+'</tr>').join(''),html=`<html><head><meta charset="utf-8"></head><body><h2>Morning Run Out Check</h2><p><b>Date:</b> ${uk(date)} &nbsp; <b>Inspector:</b> ${esc(typeof getInspector==='function'?getInspector():'')}</p><table border="1">${table}</table><br><table border="1"><tr><td>Total buses checked</td><td>${s.total}</td></tr><tr><td>On time / within 5 min</td><td>${s.on}</td></tr><tr><td>6+ min late</td><td>${s.late}</td></tr><tr><td>Run out score</td><td>${s.p.toFixed(1)}%</td></tr></table></body></html>`,blob=new Blob([html],{type:'application/vnd.ms-excel'}),url=URL.createObjectURL(blob),x=document.createElement('a');x.href=url;x.download=`Morning-Run-Out-${date}.xls`;x.click();setTimeout(()=>URL.revokeObjectURL(url),1500)}
function build(){if($('morningRunOut'))return;const nav=$('home')?.querySelector('.nav'),machine=document.querySelector('.machine');if(!nav||!machine)return;const b=document.createElement('button');b.type='button';b.dataset.open='morningRunOut';b.textContent='Morning Run Out Check';nav.insertBefore(b,nav.children[1]||null);const s=document.createElement('section');s.id='morningRunOut';s.className='section';s.innerHTML=`<button class="backBtn">← Back</button><h2>Morning Run Out Check</h2><div class="panel mroBar"><label class="fieldLabel">Run Date<input class="field" id="mroDate" type="date"></label><button class="btn" id="mroRefresh">REFRESH</button><button class="btn" id="mroExport">EXPORT EXCEL</button></div><div class="panel"><h3>Add Run Out Entry</h3><div class="grid"><input class="field" id="mroDuty" placeholder="Duty number"><input class="field" id="mroName" placeholder="Name"><input class="field" id="mroFleet" placeholder="Fleet number"></div><div class="mroChecks"><label><input type="checkbox" id="mroDqc" checked> DQC Checked</label><label><input type="checkbox" id="mroDest" checked> Correct Destination</label></div><div class="grid mroTimes"><label class="fieldLabel">Scheduled Time<input class="field" id="mroScheduled" type="time"></label><label class="fieldLabel">Actual Time Out<input class="field" id="mroActual" type="time"></label><div id="mroLive" class="mroLive">Enter scheduled and actual time</div></div><textarea class="field" id="mroComments" placeholder="Comments for this entry"></textarea><div class="grid"><button class="btn" id="mroSave">SAVE ENTRY</button><button class="btn danger" id="mroClear">CLEAR FORM</button></div></div><div class="panel small">0–5 minutes late counts as within tolerance. 6+ minutes late counts against the score.</div><div id="mroList"></div><div id="mroSummary" class="mroSummary"></div>`;machine.appendChild(s);$('mroDate').value=iso();b.onclick=()=>{typeof openSection==='function'&&openSection('morningRunOut');load()};s.querySelector('.backBtn').onclick=()=>typeof openSection==='function'&&openSection('home');$('mroDate').onchange=render;$('mroRefresh').onclick=load;$('mroExport').onclick=exportExcel;$('mroSave').onclick=save;$('mroClear').onclick=clear;$('mroScheduled').oninput=$('mroActual').oninput=live;render();load()}
function style(){if($('mroCss'))return;const s=document.createElement('style');s.id='mroCss';s.textContent=`.nav button[data-open="morningRunOut"]::before{content:'🌅'}.mroBar{display:grid;grid-template-columns:1fr auto auto;gap:8px;align-items:end}.mroChecks{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin:10px 0}.mroChecks label{background:#102b40;border:1px solid #36586f;border-radius:10px;padding:12px;color:#fff;font-weight:800}.mroChecks input{width:22px;height:22px;vertical-align:middle;margin-right:8px}.mroTimes{align-items:end}.mroLive{min-height:48px;display:flex;align-items:center;justify-content:center;text-align:center;background:#102b40;border:1px solid #36586f;border-radius:10px;font-weight:900;padding:8px}.mroLive.good,.mroCard.good{border-color:#35a86b}.mroLive.tol,.mroCard.tol{border-color:#e1a53c}.mroLive.late,.mroCard.late{border-color:#d64545}.mroCard{background:#0a1b2a;border:1px solid #36586f;border-left-width:7px;border-radius:10px;padding:11px;margin:9px 0}.mroTop{display:flex;justify-content:space-between;gap:10px}.mroTop b,.mroTop span{display:block}.mroTop span{font-size:12px;color:#b8c5ce;margin-top:3px}.mroTags{display:flex;gap:6px;flex-wrap:wrap;margin-top:8px}.mroTags span{font-size:11px;background:#213b4e;border-radius:999px;padding:4px 7px}.mroTags .ok{background:#174735;color:#8be1b7}.mroTags .bad{background:#5a1d22;color:#ffaaaa}.mroComment{margin-top:8px;padding-top:8px;border-top:1px solid #36586f}.mroSummary{display:grid;grid-template-columns:repeat(4,1fr);gap:8px;margin-top:14px}.mroSummary>div{background:#102b40;border:1px solid #36586f;border-radius:10px;text-align:center;padding:12px}.mroSummary small{display:block;color:#b8c5ce;font-weight:800}.mroSummary b{display:block;font-size:25px;margin-top:5px}.mroSummary .score{background:#123d33;border-color:#35a86b}.mroSummary .score b{color:#8be1b7}@media(max-width:650px){.mroBar{grid-template-columns:1fr 1fr}.mroBar .fieldLabel{grid-column:1/-1}.mroChecks{grid-template-columns:1fr}.mroTimes{grid-template-columns:1fr}.mroSummary{grid-template-columns:1fr 1fr}.mroTop{display:block}.mroTop strong{display:block;margin-top:6px}}`;document.head.appendChild(s)}
function init(){style();if(typeof sheets!=='undefined'&&!sheets.includes(SHEET))sheets.push(SHEET);if(typeof cloud!=='undefined'&&!cloud[SHEET])cloud[SHEET]=[];let n=0,t=setInterval(()=>{if($('home')&&document.querySelector('.machine')){clearInterval(t);build()}else if(++n>40)clearInterval(t)},250)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();