(function(){
'use strict';
const $=id=>document.getElementById(id);
let map=null,layer=null,loading=false;
const cacheKey='inspectorMapGeocodeV1';
const colours={clear:'#24a866',advised:'#e5aa22',reported:'#df3e4c',nsa:'#8b5cf6',timing:'#3788d8',early:'#f97316'};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function rows(sheet){try{const a=(typeof cloud!=='undefined'&&cloud&&Array.isArray(cloud[sheet]))?cloud[sheet]:[];if(!a.length)return[];const h=(a[0]||[]).map(v=>String(v||'').toLowerCase());return h.some(v=>['date','time','inspector','driver','fleet','service','depot','location'].includes(v))?a.slice(1):a.slice();}catch(e){return[];}}
function timeMinutes(v){const m=String(v||'').match(/(\d{1,2}):(\d{2})/);return m?Number(m[1])*60+Number(m[2]):null;}
function records(){const out=[];rows('Inspections').forEach(r=>{let type='clear';if(/offence/i.test(r[13]||''))type='reported';else if(/advis/i.test(r[13]||''))type='advised';else if(String(r[10]||'').toLowerCase()==='no')type='nsa';out.push({type,date:r[0],time:r[1],inspector:r[2],depot:r[3],driver:r[4],service:r[5],fleet:r[6],location:r[8],destination:r[9],action:r[13]||'No Driver Report',notes:r[14]||'',ref:r[15]||''});});rows('Early Running').forEach(r=>{let isEarly=false,scheduled='',actual='',minutes=null;if(r.length>=12){minutes=Number(r[10]);scheduled=r[8];actual=r[9];isEarly=Number.isFinite(minutes)&&minutes<0;}else{scheduled=r[7];actual=r[8];const sm=timeMinutes(scheduled),am=timeMinutes(actual);if(sm!==null&&am!==null){minutes=am-sm;isEarly=minutes<0;}}out.push({type:isEarly?'early':'timing',date:r[0],time:r[1],inspector:r[2],location:r.length>=12?r[3]:r[6],service:r.length>=12?r[4]:r[5],fleet:r.length>=12?r[6]:'',driver:r.length>=12?r[7]:r[3],action:isEarly?'Early Running':'Timing Check',notes:r.length>=12?r[11]:r[9],scheduled,actual,minutes});});return out.filter(x=>String(x.location||'').trim());}
function parseDate(v){if(typeof parseRowDate==='function')return parseRowDate(v);const p=String(v||'').split('/');if(p.length===3)return new Date(p[2],p[1]-1,p[0]);return new Date(v);}
function filtered(){const range=($('mapRange')||{}).value||'month',type=($('mapType')||{}).value||'all',q=(($('mapSearch')||{}).value||'').toLowerCase(),now=new Date();return records().filter(x=>{const d=parseDate(x.date);if(range==='today'&&d.toDateString()!==now.toDateString())return false;if(range==='week'){const min=new Date(now);min.setDate(now.getDate()-7);if(d<min)return false;}if(range==='month'){const min=new Date(now);min.setDate(now.getDate()-31);if(d<min)return false;}if(type!=='all'&&x.type!==type)return false;if(q&&!Object.values(x).join(' ').toLowerCase().includes(q))return false;return true;});}
function loadCache(){try{return JSON.parse(localStorage.getItem(cacheKey)||'{}')||{};}catch(e){return{};}}
function saveCache(c){try{localStorage.setItem(cacheKey,JSON.stringify(c));}catch(e){}}
async function geocode(name){const q=String(name||'').trim();if(!q)return null;try{const res=await fetch('https://nominatim.openstreetmap.org/search?format=json&limit=1&countrycodes=gb&q='+encodeURIComponent(q+', Scotland'));if(!res.ok)return null;const j=await res.json();if(!j[0])return null;return [Number(j[0].lat),Number(j[0].lon)];}catch(e){return null;}}
function dot(type){return L.divIcon({className:'inspectorMapDotWrap',html:'<span class="inspectorMapDot" style="background:'+colours[type]+'"></span>',iconSize:[22,22],iconAnchor:[11,11],popupAnchor:[0,-10]});}
function popup(x){const timing=x.type==='early'||x.type==='timing'?'<br>Scheduled: '+esc(x.scheduled||'-')+' • Actual: '+esc(x.actual||'-')+(Number.isFinite(x.minutes)?'<br>Difference: '+esc(x.minutes)+' minute'+(Math.abs(x.minutes)===1?'':'s'):''):'';return '<div class="mapPopup"><b>'+esc(x.driver||'Driver not recorded')+'</b><br>'+esc(x.date||'')+' '+esc(x.time||'')+'<br>Service: '+esc(x.service||'-')+' • Fleet: '+esc(x.fleet||'-')+'<br>Location: '+esc(x.location||'-')+'<br>Inspector: '+esc(x.inspector||'-')+'<br>Status: '+esc(x.action||x.type)+timing+(x.ref?'<br><b>Ref: '+esc(x.ref)+'</b>':'')+(x.notes?'<br>'+esc(x.notes):'')+'<br><button type="button" class="mapOpenReport" data-map-driver="'+esc(x.driver||'')+'">OPEN REPORT SEARCH</button></div>';}
async function render(){if(!map||loading)return;loading=true;const status=$('mapStatus'),data=filtered(),cache=loadCache();layer.clearLayers();let unresolved=[];data.forEach(x=>{const key=String(x.location).trim().toLowerCase();if(cache[key]){const m=L.marker(cache[key],{icon:dot(x.type)}).bindPopup(popup(x));layer.addLayer(m);}else if(!unresolved.some(y=>y.key===key))unresolved.push({key,name:x.location});});if(status)status.textContent='Showing cached locations. Finding '+unresolved.length+' new location'+(unresolved.length===1?'':'s')+'…';for(const item of unresolved.slice(0,30)){const coords=await geocode(item.name);cache[item.key]=coords||false;saveCache(cache);await new Promise(r=>setTimeout(r,950));}data.forEach(x=>{const key=String(x.location).trim().toLowerCase();if(cache[key]&&layer.getLayers().every(m=>m.options._recordKey!==key+'|'+x.date+'|'+x.driver)){const m=L.marker(cache[key],{icon:dot(x.type),_recordKey:key+'|'+x.date+'|'+x.driver}).bindPopup(popup(x));layer.addLayer(m);}});const markers=layer.getLayers();if(markers.length){const group=L.featureGroup(markers);map.fitBounds(group.getBounds().pad(.18),{maxZoom:14});}else map.setView([56.2,-3.2],7);if(status)status.textContent=markers.length+' mapped record'+(markers.length===1?'':'s')+(unresolved.length>30?' • Refresh again to locate more':'');loading=false;}
function loadLeaflet(){return new Promise((resolve,reject)=>{if(window.L)return resolve();if(!$('leafletCss')){const l=document.createElement('link');l.id='leafletCss';l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';document.head.appendChild(l);}const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=resolve;s.onerror=reject;document.body.appendChild(s);});}
function addStyle(){if($('operationsMapCss'))return;const s=document.createElement('style');s.id='operationsMapCss';s.textContent=`#operationsMapCanvas{height:62vh;min-height:430px;border-radius:12px;overflow:hidden;background:#d7e3ea}.mapControls{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:9px}.mapLegend{display:flex;flex-wrap:wrap;gap:8px;margin:8px 0;font-size:12px}.mapLegend span:before{content:'';display:inline-block;width:10px;height:10px;border-radius:50%;margin-right:5px}.lgClear:before{background:${colours.clear}}.lgAdv:before{background:${colours.advised}}.lgRep:before{background:${colours.reported}}.lgNsa:before{background:${colours.nsa}}.lgTime:before{background:${colours.timing}}.lgEarly:before{background:${colours.early}}.inspectorMapDotWrap{background:transparent;border:0}.inspectorMapDot{display:block;width:18px;height:18px;border:3px solid #fff;border-radius:50%;box-shadow:0 1px 6px rgba(0,0,0,.65)}.mapPopup{min-width:210px;line-height:1.45}.mapOpenReport{width:100%;margin-top:8px;padding:8px;border:0;border-radius:7px;background:#174f7c;color:#fff;font-weight:800}body.display-phone #operationsMapCanvas{height:55vh;min-height:360px}body.display-phone .mapControls{grid-template-columns:1fr}body.display-ipad #operationsMapCanvas{height:66vh}body.display-laptop #operationsMapCanvas{height:70vh}`;document.head.appendChild(s);}
function setup(){const nav=document.querySelector('#home .nav');if(!nav||$('operationsMap'))return;const b=document.createElement('button');b.dataset.open='operationsMap';b.innerHTML='<span class="navIcon">🗺️</span>Operations Map';nav.appendChild(b);const anchor=$('busTimes')||document.querySelector('.section:last-of-type');anchor.insertAdjacentHTML('beforebegin','<section id="operationsMap" class="section"><button class="backBtn" data-open="home">← Back</button><h2>Operations Map</h2><div class="panel"><div class="mapControls"><select class="field" id="mapRange"><option value="today">Today</option><option value="week">Last 7 Days</option><option value="month" selected>Last 31 Days</option><option value="all">All Records</option></select><select class="field" id="mapType"><option value="all">All Types</option><option value="clear">Checked OK</option><option value="advised">Advised</option><option value="reported">Offence Reports</option><option value="nsa">NSA Faults</option><option value="timing">Timing Checks</option><option value="early">Early Running Only</option></select></div><input class="searchBar" id="mapSearch" placeholder="Search driver, service, fleet, inspector or location"><div class="mapLegend"><span class="lgClear">Checked OK</span><span class="lgAdv">Advised</span><span class="lgRep">Offence</span><span class="lgNsa">NSA</span><span class="lgTime">Timing</span><span class="lgEarly">Early Running</span></div><button class="btn" id="refreshOperationsMap">REFRESH MAP</button><div class="small" id="mapStatus">Open the map to load inspection locations.</div></div><div id="operationsMapCanvas"></div></section>');['mapRange','mapType'].forEach(id=>$(id).addEventListener('change',render));$('mapSearch').addEventListener('input',()=>{clearTimeout(window._mapSearchTimer);window._mapSearchTimer=setTimeout(render,350);});$('refreshOperationsMap').onclick=render;document.addEventListener('click',e=>{const r=e.target.closest('.mapOpenReport');if(r){if(typeof openSection==='function')openSection('reportSearch');const q=$('reportSearchText');if(q){q.value=r.dataset.mapDriver||'';q.dispatchEvent(new Event('input',{bubbles:true}));}if(typeof window.renderReportSearch==='function')window.renderReportSearch();}if(e.target.closest('[data-open="operationsMap"]'))setTimeout(async()=>{try{await loadLeaflet();if(!map){map=L.map('operationsMapCanvas').setView([56.2,-3.2],7);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);layer=L.layerGroup().addTo(map);}map.invalidateSize();render();}catch(err){$('mapStatus').textContent='Map could not load. Check the internet connection.';}},180);});}
function init(){addStyle();setup();}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,900));else setTimeout(init,900);
})();