function setupV2Dom(){
 const nav=document.querySelector('.nav');
 const old=document.querySelector('[data-open="earlyRunning"]');
 if(old){old.dataset.open='timing';old.innerHTML='<span class="navIcon">⏱️</span>Timing Checks';}
 if(nav&&!document.querySelector('[data-open="coverage"]')){const b=document.createElement('button');b.dataset.open='coverage';b.innerHTML='<span class="navIcon">🗺️</span>Service Coverage';const db=document.querySelector('[data-open="database"]');db?db.after(b):nav.appendChild(b);}
 const icons={checksheet:'📋',ticket:'🎫',nsa:'🔊',driverReports:'📝',database:'🚌',busTimes:'📍',utrack:'🛰️',ticketFinder:'🔎',journeyPlanner:'🧭'};
 Object.entries(icons).forEach(([id,ic])=>{const b=document.querySelector(`[data-open="${id}"]`);if(b&&!b.querySelector('.navIcon'))b.innerHTML=`<span class="navIcon">${ic}</span>${b.textContent}`;});
 const time=$('csTimeOn');if(time)time.classList.add('timeField');
 const database=$('database');
 if(database&&!$('timing'))database.insertAdjacentHTML('beforebegin',`<section id="timing" class="section"><button class="backBtn" data-open="home">← Back</button><h2>Timing Checks</h2><div class="panel"><label class="keepRow"><input type="checkbox" id="keepTimingLocation"> Keep location after saving/clearing</label><div class="grid"><input class="field" id="tcLocation" placeholder="Location checked"><input class="field" id="tcService" placeholder="Service"><input class="field" id="tcDestination" placeholder="Destination"><input class="field" id="tcFleet" placeholder="Fleet number"><input class="field" id="tcDriver" placeholder="Driver"><input class="field timeField" id="tcScheduled" type="time" aria-label="Scheduled time"><input class="field timeField" id="tcActual" type="time" aria-label="Actual time"></div><div id="timingResult" class="timingResult neutral">Enter scheduled and actual times.</div><div class="grid2"><button class="btn" id="saveTimingBtn">SAVE TIMING CHECK</button><button class="btn danger" id="clearTimingBtn">CLEAR FORM</button></div></div><div class="panel"><div class="filterBar"><button data-timing-filter="today">Today</button><button data-timing-filter="week">This Week</button><button data-timing-filter="month">This Month</button><button data-timing-filter="all">All</button></div><input class="searchBar" id="timingSearch" placeholder="Search location, service, fleet, driver..."><button class="btn" id="exportTimingBtn">EXPORT TODAY'S TIMING CHECKS</button></div><div class="log" id="timingList"></div></section><section id="coverage" class="section"><button class="backBtn" data-open="home">← Back</button><h2>Service Coverage</h2><div class="coverageSummary" id="coverageSummary"></div><div class="panel"><input class="searchBar" id="coverageSearch" placeholder="Search service or route..."><div class="filterBar"><button data-coverage-filter="all">All</button><button data-coverage-filter="never">Never Checked</button><button data-coverage-filter="7">Last 7 Days</button><button data-coverage-filter="30">Last 30 Days</button></div><button class="btn" id="toggleServiceEditBtn">EDIT SERVICES</button><div id="serviceEditPanel" style="display:none;margin-top:10px"><div class="grid2"><input class="field" id="newServiceCode" placeholder="Service number"><input class="field" id="newServiceRoute" placeholder="Route description"></div><button class="btn" id="addServiceBtn">ADD SERVICE</button></div></div><div class="log" id="coverageList"></div></section>`);
}
setupV2Dom();
let timingFilter=localStorage.getItem('timingFilter')||'today';
let coverageFilter='all';
const defaultServices=window.INSPECTOR_SERVICES||[];
let serviceDefs=JSON.parse(localStorage.getItem('serviceCoverageList')||'null')||defaultServices;
function saveServices(){localStorage.setItem('serviceCoverageList',JSON.stringify(serviceDefs));}
function dataRows(sheet){const rows=cloud[sheet]||[];if(!rows.length)return[];const first=rows[0].map(x=>String(x||'').toLowerCase());const isHeader=first.some(x=>['date','inspector','driver','fleet','service','time'].includes(x));return isHeader?rows.slice(1):rows;}
function minutesDifference(scheduled,actual){if(!scheduled||!actual)return null;const [sh,sm]=scheduled.split(':').map(Number),[ah,am]=actual.split(':').map(Number);let diff=(ah*60+am)-(sh*60+sm);if(diff>720)diff-=1440;if(diff<-720)diff+=1440;return diff;}
function timingLabel(diff){if(diff===null)return{label:'Enter scheduled and actual times.',cls:'neutral'};if(diff===0)return{label:'ON TIME',cls:'green'};if(diff<0){const early=Math.abs(diff);return{label:`${early} MINUTE${early===1?'':'S'} EARLY`,cls:early>3?'red':'yellow'};}return{label:`${diff} MINUTE${diff===1?'':'S'} LATE`,cls:'green'};}
function updateTimingPreview(){const x=timingLabel(minutesDifference($('tcScheduled').value,$('tcActual').value));const el=$('timingResult');if(el){el.textContent=x.label;el.className='timingResult '+x.cls;}}
function clearTimingForm(){const keep=$('keepTimingLocation').checked;const location=$('tcLocation').value;['tcLocation','tcService','tcDestination','tcFleet','tcDriver','tcScheduled','tcActual'].forEach(id=>$(id).value='');if(keep)$('tcLocation').value=location;localStorage.setItem('keepTimingLocation',keep?'1':'0');localStorage.setItem('timingLocation',keep?location:'');updateTimingPreview();}
function saveTimingCheck(){const required=['tcLocation','tcService','tcScheduled','tcActual'];if(required.some(id=>!$(id).value)){alert('Please enter location, service, scheduled time and actual time.');return;}const mins=minutesDifference($('tcScheduled').value,$('tcActual').value);const result=timingLabel(mins);const row=[normaliseDateForSave(''),normaliseTimeForSave(now()),getInspector(),$('tcLocation').value,$('tcService').value,$('tcDestination').value,$('tcFleet').value,$('tcDriver').value,$('tcScheduled').value,$('tcActual').value,mins,result.label];cloudAppend('Early Running',row);if(!cloud['Early Running'])cloud['Early Running']=[];cloud['Early Running'].push(row);clearTimingForm();renderTiming();setTimeout(loadCloud,1200);}
function timingRows(){return dataRows('Early Running').filter(r=>r.length>=10);}
function renderTiming(){const el=$('timingList');if(!el)return;const q=(($('timingSearch')||{}).value||'').toLowerCase(),n=new Date();let rows=timingRows().filter(r=>{const d=parseRowDate(r[0]);if(timingFilter==='today'&&!sameDay(d,n))return false;if(timingFilter==='week'&&!inThisWeek(d))return false;if(timingFilter==='month'&&!inThisMonth(d))return false;return!q||r.join(' ').toLowerCase().includes(q);});el.innerHTML=rows.reverse().map(r=>{const mins=Number(r[10]);const x=timingLabel(isNaN(mins)?minutesDifference(r[8],r[9]):mins);return `<div class="timingCard ${x.cls}"><b>${r[4]||'-'} • ${x.label}</b><div>${formatDateValue(r[0])} ${formatTimeValue(r[1])}</div><div>${r[3]||'-'} • ${r[5]||'-'}</div><div>Fleet ${r[6]||'-'} • ${r[7]||'-'} • ${r[2]||'-'}</div><div>Scheduled ${formatTimeValue(r[8])} • Actual ${formatTimeValue(r[9])}</div></div>`;}).join('')||'No timing checks for this view.';}
function exportTimingToday(){const n=new Date(),rows=timingRows().filter(r=>sameDay(parseRowDate(r[0]),n));const out=['Date,Time,Inspector,Location,Service,Destination,Fleet,Driver,Scheduled,Actual,Minutes,Result'];rows.forEach(r=>out.push(r.map(esc).join(',')));download('Timing-Checks-'+n.toISOString().slice(0,10)+'.csv',out.join('\n'));}
function normaliseService(v){return String(v||'').toUpperCase().replace(/\s+/g,'').replace(/[^A-Z0-9]/g,'');}
function serviceLastChecks(){const map={};dataRows('Inspections').forEach(r=>{const key=normaliseService(r[5]);if(!key)return;const item={date:r[0],inspector:r[2],driver:r[4],fleet:r[6],depot:r[3]};if(!map[key]||parseRowDate(item.date)>parseRowDate(map[key].date))map[key]=item;});return map;}
function renderCoverage(){const el=$('coverageList');if(!el)return;const q=(($('coverageSearch')||{}).value||'').toLowerCase(),last=serviceLastChecks(),nowDate=new Date();let rows=serviceDefs.map((s,i)=>({...s,i,last:last[normaliseService(s.code)]||null}));rows=rows.filter(x=>{if(q&&!(`${x.code} ${x.route}`).toLowerCase().includes(q))return false;if(coverageFilter==='never')return!x.last;if(coverageFilter==='7'||coverageFilter==='30'){if(!x.last)return false;const age=(nowDate-parseRowDate(x.last.date))/86400000;return age<=Number(coverageFilter);}return true;});rows.sort((a,b)=>{if(!a.last&&!b.last)return a.code.localeCompare(b.code,undefined,{numeric:true});if(!a.last)return-1;if(!b.last)return 1;return parseRowDate(a.last.date)-parseRowDate(b.last.date);});const edit=$('serviceEditPanel')?.style.display!=='none';el.innerHTML=rows.map(x=>{let cls='never',meta='Never checked';if(x.last){const age=(nowDate-parseRowDate(x.last.date))/86400000;cls=age<=7?'recent':'old';meta=`Last checked ${formatDateValue(x.last.date)} by ${x.last.inspector||'-'} • Fleet ${x.last.fleet||'-'} • Driver ${x.last.driver||'-'}`;}return `<div class="coverageCard ${cls}"><div class="coverageTop"><div><div class="coverageCode">${x.code}</div><div class="coverageRoute">${x.route}</div></div>${edit?`<button class="btn danger serviceDelete" data-delete-service="${x.i}">Remove</button>`:''}</div><div class="coverageMeta">${meta}</div></div>`;}).join('')||'No services match.';const total=serviceDefs.length,checked=serviceDefs.filter(s=>last[normaliseService(s.code)]).length,never=total-checked,recent=serviceDefs.filter(s=>{const x=last[normaliseService(s.code)];return x&&(nowDate-parseRowDate(x.date))/86400000<=7;}).length;$('coverageSummary').innerHTML=`<div class="coverageStat"><b>${total}</b>Total</div><div class="coverageStat"><b>${checked}</b>Checked</div><div class="coverageStat"><b>${recent}</b>Last 7 Days</div><div class="coverageStat"><b>${never}</b>Never</div>`;}
function buildDriversV2(){const d={};dataRows('Inspections').forEach(r=>{const name=(r[4]||'').trim();if(!name)return;if(!d[name])d[name]={name,inspections:0,nsa:0,reports:0,last:null,history:[]};const x=d[name];x.inspections++;if(r[10]==='No')x.nsa++;if(r[13]&&r[13]!=='No Driver Report')x.reports++;const item={date:r[0],service:r[5],fleet:r[6],inspector:r[2]};if(!x.last||parseRowDate(item.date)>parseRowDate(x.last.date))x.last=item;x.history.push(`${formatDateValue(r[0])} • ${r[5]||'-'} • Fleet ${r[6]||'-'} • ${r[2]||'-'}`);});return Object.values(d);}
function buildFleetsV2(){const f={};dataRows('Inspections').forEach(r=>{const fleet=(r[6]||'').trim();if(!fleet)return;if(!f[fleet])f[fleet]={fleet,inspections:0,nsa:0,reports:0,last:null,history:[]};const x=f[fleet];x.inspections++;if(r[10]==='No')x.nsa++;if(r[13]&&r[13]!=='No Driver Report')x.reports++;const item={date:r[0],service:r[5],driver:r[4],inspector:r[2]};if(!x.last||parseRowDate(item.date)>parseRowDate(x.last.date))x.last=item;x.history.push(`${formatDateValue(r[0])} • ${r[5]||'-'} • ${r[4]||'-'} • ${r[2]||'-'}`);});return Object.values(f);}
function renderDatabaseV2(){const de=$('driverDbList'),fe=$('fleetDbList');if(!de||!fe)return;const dq=(($('driverSearch')||{}).value||'').toLowerCase(),fq=(($('fleetSearch')||{}).value||'').toLowerCase();de.innerHTML=buildDriversV2().filter(x=>x.name.toLowerCase().includes(dq)).sort((a,b)=>a.name.localeCompare(b.name)).map(d=>`<div class="dbCard driver"><h3>${d.name}</h3><div class="small">Last checked: ${d.last?formatDateValue(d.last.date)+' • '+(d.last.service||'-')+' • Fleet '+(d.last.fleet||'-'):'-'}</div><div class=dbStats><div class=dbStat><b>${d.inspections}</b>Inspections</div><div class=dbStat><b>${d.nsa}</b>NSA</div><div class=dbStat><b>${d.reports}</b>Reports</div></div><details><summary>History</summary>${d.history.reverse().map(h=>`<div class=small>${h}</div>`).join('')}</details></div>`).join('')||'No drivers.';fe.innerHTML=buildFleetsV2().filter(x=>x.fleet.toLowerCase().includes(fq)).sort((a,b)=>a.fleet.localeCompare(b.fleet,undefined,{numeric:true})).map(f=>`<div class="dbCard fleet"><h3>Fleet ${f.fleet}</h3><div class="small">Last checked: ${f.last?formatDateValue(f.last.date)+' • '+(f.last.service||'-')+' • '+(f.last.driver||'-'):'-'}</div><div class=dbStats><div class=dbStat><b>${f.inspections}</b>Inspections</div><div class=dbStat><b>${f.nsa}</b>NSA</div><div class=dbStat><b>${f.reports}</b>Reports</div></div><details><summary>History</summary>${f.history.reverse().map(h=>`<div class=small>${h}</div>`).join('')}</details></div>`).join('')||'No fleet.';}
renderDatabase=renderDatabaseV2;
const originalRenderAll=renderAll;renderAll=function(){originalRenderAll();renderTiming();renderCoverage();renderDatabaseV2();};
document.addEventListener('click',e=>{const tf=e.target.dataset.timingFilter;if(tf){timingFilter=tf;localStorage.setItem('timingFilter',tf);renderTiming();}const cf=e.target.dataset.coverageFilter;if(cf){coverageFilter=cf;renderCoverage();}const del=e.target.dataset.deleteService;if(del!==undefined){serviceDefs.splice(Number(del),1);saveServices();renderCoverage();}});
document.addEventListener('input',e=>{if(e.target.id==='tcScheduled'||e.target.id==='tcActual')updateTimingPreview();if(e.target.id==='timingSearch')renderTiming();if(e.target.id==='coverageSearch')renderCoverage();});
window.addEventListener('load',()=>{const keep=localStorage.getItem('keepTimingLocation')==='1';$('keepTimingLocation').checked=keep;if(keep)$('tcLocation').value=localStorage.getItem('timingLocation')||'';$('saveTimingBtn').onclick=saveTimingCheck;$('clearTimingBtn').onclick=clearTimingForm;$('exportTimingBtn').onclick=exportTimingToday;$('toggleServiceEditBtn').onclick=()=>{const p=$('serviceEditPanel');p.style.display=p.style.display==='none'?'block':'none';renderCoverage();};$('addServiceBtn').onclick=()=>{const code=$('newServiceCode').value.trim(),route=$('newServiceRoute').value.trim();if(!code)return;serviceDefs.push({code,route});saveServices();$('newServiceCode').value='';$('newServiceRoute').value='';renderCoverage();};renderTiming();renderCoverage();renderDatabaseV2();});
